name: Code Check
on:
  - workflow_dispatch
  - workflow_call
  - pull_request
jobs:
  build:
    uses: "./.github/workflows/build.yml"
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Lint
        run: |
          npm install
          npm run lint
