name: Draft Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    uses: "./.github/workflows/build.yml"
  draft:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Create Draft
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="Release v$tag" \
            --draft \
            main.js manifest.json styles.css
